version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your Nginx config file
    networks:
      - ecommerce_network  # Nginx container network (can be omitted if just accessing host)

networks:
  ecommerce_network:
    driver: bridge  # Optional, only if needed
