version: '3'

services:
  redis-node-1:
    image: redis:7.2
    container_name: redis-node-1
    command: redis-server /usr/local/etc/redis/node-1.conf
    ports:
      - "7001:7001"
    volumes:
      - ./config-node/node-1.conf:/usr/local/etc/redis/node-1.conf
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:7.2
    container_name: redis-node-2
    command: redis-server /usr/local/etc/redis/node-2.conf
    ports:
      - "7002:7002"
    volumes:
      - ./config-node/node-2.conf:/usr/local/etc/redis/node-2.conf
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:7.2
    container_name: redis-node-3
    command: redis-server /usr/local/etc/redis/node-3.conf
    ports:
      - "7003:7003"
    volumes:
      - ./config-node/node-3.conf:/usr/local/etc/redis/node-3.conf
    networks:
      - redis-cluster

  redis-node-4:
    image: redis:7.2
    container_name: redis-node-4
    command: redis-server /usr/local/etc/redis/node-4.conf
    ports:
      - "7004:7004"
    volumes:
      - ./config-node/node-4.conf:/usr/local/etc/redis/node-4.conf
    networks:
      - redis-cluster

  redis-node-5:
    image: redis:7.2
    container_name: redis-node-5
    command: redis-server /usr/local/etc/redis/node-5.conf
    ports:
      - "7005:7005"
    volumes:
      - ./config-node/node-5.conf:/usr/local/etc/redis/node-5.conf
    networks:
      - redis-cluster

  redis-node-6:
    image: redis:7.2
    container_name: redis-node-6
    command: redis-server /usr/local/etc/redis/node-6.conf
    ports:
      - "7006:7006"
    volumes:
      - ./config-node/node-6.conf:/usr/local/etc/redis/node-6.conf
    networks:
      - redis-cluster

  redis-node-7:
    image: redis:7.2
    container_name: redis-node-7
    command: redis-server /usr/local/etc/redis/node-7.conf
    ports:
      - "7007:7007"
    volumes:
      - ./config-node/node-7.conf:/usr/local/etc/redis/node-7.conf
    networks:
      - redis-cluster

  redis-node-8:
    image: redis:7.2
    container_name: redis-node-8
    command: redis-server /usr/local/etc/redis/node-8.conf
    ports:
      - "7008:7008"
    volumes:
      - ./config-node/node-8.conf:/usr/local/etc/redis/node-8.conf
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge
